# Kendall's tau of the absolute spherical t copula on a grid of degrees of
# freedom, for astcopula_tau() and astcopula_nu(). Writes
# R/astcopula-tau-table.R. Run from the package root.
#
# ast_tau_exact() integrates 1 - 4 int int h1 h2 by tensor tanh-sinh quadrature;
# N = 1600 nodes per variable is converged to ~1e-9 down to nu = 0.02.

devtools::load_all(quiet = TRUE) # for ast_tau_exact()

nu <- exp(seq(log(0.02), log(2000), length.out = 181))
tau <- vapply(nu, ast_tau_exact, 0, N = 1600L)
stopifnot(all(diff(tau) < 0))

fmt <- function(x) {
  lines <- strwrap(paste(sprintf("%.15g", x), collapse = ", "), width = 90)
  paste0("  ", lines, collapse = "\n")
}
writeLines(c(
  "# Generated by data-raw/astcopula-tau.R -- do not edit.",
  "# Kendall's tau of the absolute spherical t copula at a log-spaced grid of",
  "# degrees of freedom; see astcopula_tau().",
  "ast_tau_table <- list(",
  "  nu = c(", sub(",$", "", fmt(nu)), "  ),",
  "  tau = c(", sub(",$", "", fmt(tau)), "  )",
  ")"
), "R/astcopula-tau-table.R")
